### ISSUE TITLE
Erro na geração de relatórios de salas

### ISSUE THREAD

**Issue by joaoCS** [npsoftuva/lotacaoprofessores#62]
As aulas estão sendo impressas deslocadas uma célula para a direita. Assim, aulas da segunda estão sendo impressas na terça, as aulas de Terça-Feira estão sendo impressas na quarta e assim por diante. As aulas de sexta-feira estão sendo impressas fora da tabela

**Comment by joaoCS** [comment]
Corrigi essa issue, mas falta dar um commit.

**Comment by alanvasconcelos** [comment]
Issue resolvida.
