### ISSUE TITLE
Usuário não está sendo excluído.

### ISSUE THREAD

**Issue by joaoCS** [npsoftuva/lotacaoprofessores#63]
No menu usuários, não está sendo possível excluir usuários. Porém, ao realizar a operação de exclusão, aparece uma mensagem informando sobre o sucesso da exclusão, mas a operação não é bem sucedida.

**Comment by joaoCS** [comment]
É um problema com o banco postgress, pois tentei fazer a operação direto no pgAdmin e não deu certo.

**Comment by alanvasconcelos** [comment]
Bug foi encontrado em uma trigger no BD e foi resolvido.
